server:
  port: 9000

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017/roj_ci_db
    redis:
      database: 4
      host: localhost
      port: 6379
      password: 123456
      timeout: 10000
  cache:
    type: redis